spring:
   datasource:
      url: jdbc:mysql://localhost:3307/im_admin_management
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Temp1234
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
   zipkin:
      base-url: http://localhost:9411
